### ISSUE TITLE
hello please i am having problem building

### ISSUE THREAD

**Issue by Balogunolalere** [ScRiPt1337/Teardroid-phprat#30]
Notification Title : Google
Notification Content : system update
Notification Subtext : today
[+] Changing app name to teardroid!
[+] Changing app name completed!
[+] Changing hostname to https://a3xiyc.deta.dev!
[+] Changing hostname completed!
[+] Changing notification title to Google!
[+] Changing notification content to system update!
[+] Changing notification subtext to today!
[+] Changing notification completed!
[+] Compiling Teardroid using apktool!
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.AndrolibException: java.io.FileNotFoundException: /home/jamal/.local/share/apktool/framework/1.apk (No such file or directory)
[+] Compiling Teardroid completed!
[+] Compressing APK Files using zipalign!
Unable to open 'teardroid_uncompressed.apk' as zip archive
[+] Signing Teardroid!
Exception in thread "main" java.io.FileNotFoundException: teardroid.apk (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:190)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:381)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)
Traceback (most recent call last):
  File "Teardroid.py", line 83, in <module>
    builder(args.build)
  File "Teardroid.py", line 71, in builder
    Teardroid.Clear()
  File "/home/jamal/Teardroid-phprat/Builder.py", line 82, in Clear
    os.remove(self.name + ".apk.idsig")
FileNotFoundError: [Errno 2] No such file or directory: 'teardroid.apk.idsig'

**Comment by ScRiPt1337** [comment]
which version of os your using

**Comment by NUCLIE-X** [comment]
same issue i am facing

**Comment by ScRiPt1337** [comment]
> hich version of os your using

which os your using
