### ISSUE TITLE
Failed to load signer "signer #1"                                         

### ISSUE THREAD

**Issue by recoyeb** [ScRiPt1337/Teardroid-phprat#45]
Failed to load signer "signer #1"                                         
java.io.IOException: Invalid keystore format                              
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:666)                                                                     
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:57)                                                                  
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:215)                                                           
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)                                                        
        at java.security.KeyStore.load(KeyStore.java:1445)                
        at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:362)                                                           
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:248)                                             
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)                                                         
        at com.android.apksigner.ApkSignerTool.getSignerConfig(ApkSignerTool.java:405)                                                              
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:324)                                                                         
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)
Traceback (most recent call last):                                        
  File "/home/kali/Teardroid-phprat/Teardroid.py", line 103, in <module>  
    builder(args.build)                                                   
  File "/home/kali/Teardroid-phprat/Teardroid.py", line 87, in builder    
    Teardroid.Clear()                                                     
  File "/home/kali/Teardroid-phprat/Builder.py", line 89, in Clear        
    os.remove(self.name + ".apk.idsig")                                   
FileNotFoundError: [Errno 2] No such file or directory: 'com_update_service.apk.idsig'

**Comment by ScRiPt1337** [comment]
try it on some other os
