### ISSUE TITLE
"control panel not opening"

### ISSUE THREAD

**Issue by Rocky8088** [ScRiPt1337/Teardroid-phprat#50]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
"It can show me only"Hello, world" and this brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_127028542788686989528405215824808772966.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 32, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL6622058409058653428.tmp, -e, /tmp/APKTOOL2980092642000179113.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Teardroid-phprat/Teardroid_Payload/res, -M, /root/Teardroid-phprat/Teardroid_Payload/AndroidManifest.xml]
[+] Compiling Teardroid completed! ✓
[+] Compressing APK Files using zipalign! ✓
sh: 1: /root/Teardroid-phprat/zipalign: not found
[+] Signing Teardroid! ✓
Exception in thread "main" java.io.FileNotFoundException: rocky.apk (No such file or directory)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:190)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:381)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)
Traceback (most recent call last):
  File "/root/Teardroid-phprat/Teardroid.py", line 103, in <module>
    builder(args.build)
  File "/root/Teardroid-phprat/Teardroid.py", line 87, in builder
    Teardroid.Clear()
  File "/root/Teardroid-phprat/Builder.py", line 89, in Clear
    os.remove(self.name + ".apk.idsig")
FileNotFoundError: [Errno 2] No such file or directory: 'rocky.apk.idsig'

**Comment by ScRiPt1337** [comment]
PLease fill the proper device information

**Comment by ScRiPt1337** [comment]
and please explain what is the exact problem your facing
