### ISSUE TITLE
hi brother can you help me to see what is going on, I use Ubuntu vps, thank you

### ISSUE THREAD

**Issue by root26** [ScRiPt1337/Teardroid-phprat#64]
[+] Please navigate to the website https://easyappicon.com using your preferred web browser.
From there, you may upload the desired image to be used as the icon for your application.
The website will generate a compressed ZIP file containing all the necessary files.
Once the ZIP file has been downloaded,
extract its contents to a folder of your choosing.
inside that folder there will be a android folder containing all the necessary files.
copy the android folder full path and paste it into the promote.
or leave it blank if you want to use the default icon.
example: D:\xxxx\ic_launcher-6446b783efdd6\ic_launcher-6446b783efdd6\android! ✓
Android icon folder path (leave blank if you wanna go with the default icon):
[+] using the default keystore to sing the apk its not recommended! ✓
[+] create a new keystore and change the values in the config.py file to use your own keystore instead! ✓
[+] Changing app name to hello! ✓
[+] Changing app name completed! ✓
[+] Changing hostname to https://szqllmgagc-1-k9109765.deta.app! ✓
[+] Changing hostname completed! ✓
[+] Changing fake web homepage to ! ✓
[+] Changing fake web homepage completed! ✓
[+] Changing notification title to ! ✓
[+] Changing notification content to ! ✓
[+] Changing notification subtext to ! ✓
[+] Changing notification completed! ✓
[+] Compiling Teardroid using apktool! ✓
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Killed
[+] Compiling Teardroid completed! ✓
[+] Compressing APK Files using zipalign! ✓
Unable to open 'hello_uncompressed.apk' as zip archive
[+] Signing Teardroid! ✓
Exception in thread "main" java.io.FileNotFoundException: hello.apk (No such file or directory)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:190)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:381)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)
Traceback (most recent call last):
  File "/root/Teardroid-phprat/Teardroid.py", line 127, in <module>
    builder(args.build)
  File "/root/Teardroid-phprat/Teardroid.py", line 111, in builder
    Teardroid.Clear()
  File "/root/Teardroid-phprat/Builder.py", line 115, in Clear
    os.remove(self.name + ".apk.idsig")
FileNotFoundError: [Errno 2] No such file or directory: 'hello.apk.idsig'
root@FoolishFaroff-VM:~/Teardroid-phprat#

**Comment by ScRiPt1337** [comment]
compiling process got killed Killed reboot your server or pc  what ever your using and make sure you got good amount free ram like 500 mb free ram
