### ISSUE TITLE
Error in building apk

### ISSUE THREAD

**Issue by icrner23** [ScRiPt1337/Teardroid-phprat#71]
when creating apk this error show how can i fix it?

←[33m[+] Compiling Teardroid using apktool! ✓
'C:\Users\Shayan_PC\Documents\Teadroid' is not recognized as an internal or external command,
operable program or batch file.
[+] Compiling Teardroid completed! ✓
[+] Compressing APK Files using zipalign! ✓
'C:\Users\Shayan_PC\Documents\Teadroid' is not recognized as an internal or external command,
operable program or batch file.
[+] Signing Teardroid! ✓
'C:\Users\Shayan_PC\Documents\Teadroid' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\Shayan_PC\Documents\Teadroid android rat\Teardroid-phprat\Teardroid.py", line 128, in <module>
    builder(args.build)
  File "C:\Users\Shayan_PC\Documents\Teadroid android rat\Teardroid-phprat\Teardroid.py", line 112, in builder
    Teardroid.Clear()
  File "C:\Users\Shayan_PC\Documents\Teadroid android rat\Teardroid-phprat\Builder.py", line 115, in Clear
    os.remove(self.name + ".apk.idsig")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'IcyAntivirus.apk.idsig'

![photo_2023-07-07_15-30-51](https://github.com/ScRiPt1337/Teardroid-phprat/assets/128067076/e30dc515-d16e-4021-b03b-7c54966a69d5)

**Comment by ScRiPt1337** [comment]
dont use space in path name
